### ISSUE TITLE
Produced repo has incorrect paths to charts

### ISSUE THREAD

**Issue by ross-w** [mrsimonemms/nvidia-helm-mirror#1]
### Bug description

It appears the produced `index.yaml` file in the mirror is expecting the chart tarballs to be in `charts/` but the actual files are present in `.`

Example (but they're all the same):

```
 gpu-operator:
  - apiVersion: v2
    appVersion: v25.3.0
    created: "2025-03-26T18:17:20Z"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: v0.17.2
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: fa464048fd0fcb0ba5d8063cbaaec48f8264d6bc8fb7d6bcdaac2beeceea8551
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - charts/gpu-operator-v25.3.0.tgz
    version: v25.3.0
```

This results in a 404 for every chart when attempting to install from the repo.

### Steps to reproduce

```
helm repo add nvidia-mirror https://mrsimonemms.github.io/nvidia-helm-mirror \
    && helm repo update
```
followed by
```
helm install gpu-operator nvidia-mirror/gpu-operator
```
Yields:
```
Error: INSTALLATION FAILED: failed to fetch https://mrsimonemms.github.io/nvidia-helm-mirror/charts/gpu-operator-v25.3.0.tgz : 404 Not Found
```

### Expected behaviour

Helm chart installs successfully

### Anything else?

I suspect something has changed recently, but I can't tell if it's on the nvidia side or on the helm-mirror side. 

Nvidia briefly published their own repo on github, but their github pages is not being updated from the source repo branch (and is therefore stuck several versions behind.) This may be entirely unrelated.
